# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burndown_for_what', '0002_daily_score_unplanned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='notify_closed',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='notify_daily',
        ),
        migrations.AddField(
            model_name='sprint',
            name='github_repo',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='github_user',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='github_milestone_id',
            field=models.IntegerField(default=0),
        ),
    ]
