# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-31 01:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burndown_for_what', '0003_auto_20160331_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('github_id', models.IntegerField(default=0)),
                ('url', models.TextField()),
                ('number', models.IntegerField(default=0)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('assignee_login', models.CharField(blank=True, max_length=150, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('unplanned', models.NullBooleanField()),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burndown_for_what.Sprint')),
            ],
        ),
    ]
