# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-14 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burndown_for_what', '0005_remove_sprint_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=150)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burndown_for_what.Issue')),
            ],
        ),
    ]
